name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  build_and_publish_image:
    name: Build and publish image
    runs-on: ubuntu-latest
    environment: production

    permissions: 
      contents: read
      packages: write

    steps:
    - name: echo
      run: echo ${{ github.GITHUB_TOKEN }}
      
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to container registry
      uses: docker/login-action@v3.1.0
      with: 
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }} 
        NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} 
        NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} 
        GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} 
        GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} 
        YT_API_KEY=${{ secrets.YT_API_KEY }}" > .env

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: test
      run: ls -la
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with: 
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
