name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
    
jobs:
  build_and_publish_image:
    name: Build and publish image
    runs-on: ubuntu-latest

    permissions: 
      contents: read
      packages: write

    steps:
    - name: echo
      run: echo ${{ github.GITHUB_TOKEN }}
      
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to container registry
      uses: docker/login-action@v3.1.0
      with: 
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with: 
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
